version: '3.7'

services:
  heimdall:
    build:
      context: .
      target: development
    restart: always
    container_name: heimdall
    env_file: ./env/dev.env
    ports:
      - '5000:5000'
      - '6789:5678'
    volumes:
      - ./:/app

  heimdall-test:
    build:
      context: .
      target: test
    container_name: heimdall-test
    env_file: ./env/test.env
    volumes:
      - ./:/app

  heimdall-db:
    image: postgres:12-alpine
    restart: always
    container_name: heimdall-db
    env_file: ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
