version: '3.7'

services:
  heimdall:
    image: python:3.8-slim
    restart: always
    container_name: heimdall
    entrypoint: [./entrypoint.sh, development]
    env_file: ./env/dev.env
    ports:
      - '5000:5000'
    working_dir: /app
    volumes:
      - ./:/app

  heimdall-db:
    image: postgres:12-alpine
    restart: always
    container_name: heimdall-db
    env_file: ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
