"""Add permission table

Revision ID: 4db56fb65145
Revises: fe1543c62d8d
Create Date: 2020-10-31 09:46:47.101714

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4db56fb65145'
down_revision = 'fe1543c62d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'permissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
