// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createBackupCodes = `-- name: CreateBackupCodes :batchexec
INSERT INTO mfa_backup_codes (user_id, tenant_id, code_hash)
VALUES ($1, $2, $3)
`

type CreateBackupCodesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBackupCodesParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	CodeHash string    `json:"code_hash"`
}

func (q *Queries) CreateBackupCodes(ctx context.Context, arg []CreateBackupCodesParams) *CreateBackupCodesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.TenantID,
			a.CodeHash,
		}
		batch.Queue(createBackupCodes, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBackupCodesBatchResults{br, len(arg), false}
}

func (b *CreateBackupCodesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateBackupCodesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
