// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_attempts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteOldLoginAttempts = `-- name: DeleteOldLoginAttempts :exec
DELETE FROM login_attempts
WHERE attempted_at < $1
`

// Cleanup query to delete login attempts older than the specified time
// Should be run periodically (e.g., daily via cron job)
func (q *Queries) DeleteOldLoginAttempts(ctx context.Context, attemptedAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldLoginAttempts, attemptedAt)
	return err
}

const getMostRecentLockout = `-- name: GetMostRecentLockout :one
SELECT locked_until
FROM login_attempts
WHERE email = $1
  AND locked_until IS NOT NULL
ORDER BY attempted_at DESC
LIMIT 1
`

// Gets the most recent non-null locked_until for checking active lockouts
func (q *Queries) GetMostRecentLockout(ctx context.Context, email string) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getMostRecentLockout, email)
	var locked_until *time.Time
	err := row.Scan(&locked_until)
	return locked_until, err
}

const getRecentFailedAttempts = `-- name: GetRecentFailedAttempts :one
SELECT COUNT(*) as count
FROM login_attempts
WHERE email = $1
  AND attempted_at > $2
`

type GetRecentFailedAttemptsParams struct {
	Email       string    `json:"email"`
	AttemptedAt time.Time `json:"attempted_at"`
}

func (q *Queries) GetRecentFailedAttempts(ctx context.Context, arg GetRecentFailedAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentFailedAttempts, arg.Email, arg.AttemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :one
INSERT INTO login_attempts (
    email,
    user_id,
    ip_address,
    locked_until
) VALUES (
    $1, $2, $3, $4
) RETURNING id, email, user_id, ip_address, locked_until, attempted_at, created_at
`

type InsertLoginAttemptParams struct {
	Email       string     `json:"email"`
	UserID      *uuid.UUID `json:"user_id"`
	IpAddress   string     `json:"ip_address"`
	LockedUntil *time.Time `json:"locked_until"`
}

func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, insertLoginAttempt,
		arg.Email,
		arg.UserID,
		arg.IpAddress,
		arg.LockedUntil,
	)
	var i LoginAttempt
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.IpAddress,
		&i.LockedUntil,
		&i.AttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}
