// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_settings.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMFASettings = `-- name: CreateMFASettings :one
INSERT INTO mfa_settings (
    user_id,
    tenant_id,
    totp_secret
) VALUES ($1, $2, $3)
RETURNING user_id, tenant_id, totp_secret, last_used_window, created_at, verified_at, last_used_at
`

type CreateMFASettingsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	TotpSecret string    `json:"totp_secret"`
}

func (q *Queries) CreateMFASettings(ctx context.Context, arg CreateMFASettingsParams) (MfaSetting, error) {
	row := q.db.QueryRow(ctx, createMFASettings, arg.UserID, arg.TenantID, arg.TotpSecret)
	var i MfaSetting
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.TotpSecret,
		&i.LastUsedWindow,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteMFASettings = `-- name: DeleteMFASettings :exec
DELETE FROM mfa_settings WHERE user_id = $1
`

func (q *Queries) DeleteMFASettings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMFASettings, userID)
	return err
}

const getMFASettingsByUserID = `-- name: GetMFASettingsByUserID :one
SELECT user_id, tenant_id, totp_secret, last_used_window, created_at, verified_at, last_used_at FROM mfa_settings WHERE user_id = $1
`

func (q *Queries) GetMFASettingsByUserID(ctx context.Context, userID uuid.UUID) (MfaSetting, error) {
	row := q.db.QueryRow(ctx, getMFASettingsByUserID, userID)
	var i MfaSetting
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.TotpSecret,
		&i.LastUsedWindow,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateMFASettings = `-- name: UpdateMFASettings :exec
UPDATE mfa_settings
SET
    last_used_window = $2,
    verified_at = $3,
    last_used_at = $4
WHERE user_id = $1
`

type UpdateMFASettingsParams struct {
	UserID         uuid.UUID  `json:"user_id"`
	LastUsedWindow *int64     `json:"last_used_window"`
	VerifiedAt     *time.Time `json:"verified_at"`
	LastUsedAt     *time.Time `json:"last_used_at"`
}

func (q *Queries) UpdateMFASettings(ctx context.Context, arg UpdateMFASettingsParams) error {
	_, err := q.db.Exec(ctx, updateMFASettings,
		arg.UserID,
		arg.LastUsedWindow,
		arg.VerifiedAt,
		arg.LastUsedAt,
	)
	return err
}
