// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_backup_codes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUnusedBackupCodes = `-- name: CountUnusedBackupCodes :one
SELECT COUNT(*) FROM mfa_backup_codes
WHERE user_id = $1 AND used = false
`

func (q *Queries) CountUnusedBackupCodes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedBackupCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBackupCodesByUserID = `-- name: DeleteBackupCodesByUserID :exec
DELETE FROM mfa_backup_codes WHERE user_id = $1
`

func (q *Queries) DeleteBackupCodesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupCodesByUserID, userID)
	return err
}

const getUnusedBackupCodesByUserID = `-- name: GetUnusedBackupCodesByUserID :many
SELECT id, user_id, code_hash, used, used_at, created_at FROM mfa_backup_codes
WHERE user_id = $1 AND used = false
ORDER BY created_at ASC
`

func (q *Queries) GetUnusedBackupCodesByUserID(ctx context.Context, userID uuid.UUID) ([]MfaBackupCode, error) {
	rows, err := q.db.Query(ctx, getUnusedBackupCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MfaBackupCode{}
	for rows.Next() {
		var i MfaBackupCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.Used,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupCodeUsed = `-- name: MarkBackupCodeUsed :exec
UPDATE mfa_backup_codes
SET used = true, used_at = now()
WHERE id = $1
`

func (q *Queries) MarkBackupCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackupCodeUsed, id)
	return err
}
