// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOIDCSession = `-- name: CreateOIDCSession :one
INSERT INTO oidc_sessions (
    state,
    code_verifier,
    oidc_provider_id,
    provider_type,
    redirect_uri,
    tenant_id,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, state, code_verifier, oidc_provider_id, provider_type, redirect_uri, tenant_id, created_at, expires_at
`

type CreateOIDCSessionParams struct {
	State          string               `json:"state"`
	CodeVerifier   string               `json:"code_verifier"`
	OidcProviderID *uuid.UUID           `json:"oidc_provider_id"`
	ProviderType   NullOidcProviderType `json:"provider_type"`
	RedirectUri    string               `json:"redirect_uri"`
	TenantID       *uuid.UUID           `json:"tenant_id"`
	ExpiresAt      time.Time            `json:"expires_at"`
}

func (q *Queries) CreateOIDCSession(ctx context.Context, arg CreateOIDCSessionParams) (OidcSession, error) {
	row := q.db.QueryRow(ctx, createOIDCSession,
		arg.State,
		arg.CodeVerifier,
		arg.OidcProviderID,
		arg.ProviderType,
		arg.RedirectUri,
		arg.TenantID,
		arg.ExpiresAt,
	)
	var i OidcSession
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CodeVerifier,
		&i.OidcProviderID,
		&i.ProviderType,
		&i.RedirectUri,
		&i.TenantID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredOIDCSessions = `-- name: DeleteExpiredOIDCSessions :exec
DELETE FROM oidc_sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredOIDCSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOIDCSessions)
	return err
}

const deleteOIDCSession = `-- name: DeleteOIDCSession :exec
DELETE FROM oidc_sessions
WHERE id = $1
`

func (q *Queries) DeleteOIDCSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOIDCSession, id)
	return err
}

const getOIDCSessionByState = `-- name: GetOIDCSessionByState :one
SELECT id, state, code_verifier, oidc_provider_id, provider_type, redirect_uri, tenant_id, created_at, expires_at FROM oidc_sessions
WHERE state = $1 AND expires_at > now()
`

func (q *Queries) GetOIDCSessionByState(ctx context.Context, state string) (OidcSession, error) {
	row := q.db.QueryRow(ctx, getOIDCSessionByState, state)
	var i OidcSession
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CodeVerifier,
		&i.OidcProviderID,
		&i.ProviderType,
		&i.RedirectUri,
		&i.TenantID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
