// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: oidc_links.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOIDCLink = `-- name: CreateOIDCLink :one
INSERT INTO oidc_links (
    user_id,
    oidc_provider_id,
    provider_user_id,
    provider_email,
    provider_metadata
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, oidc_provider_id, provider_user_id, provider_email, provider_metadata, linked_at, last_used_at
`

type CreateOIDCLinkParams struct {
	UserID           uuid.UUID `json:"user_id"`
	OidcProviderID   uuid.UUID `json:"oidc_provider_id"`
	ProviderUserID   string    `json:"provider_user_id"`
	ProviderEmail    string    `json:"provider_email"`
	ProviderMetadata []byte    `json:"provider_metadata"`
}

func (q *Queries) CreateOIDCLink(ctx context.Context, arg CreateOIDCLinkParams) (OidcLink, error) {
	row := q.db.QueryRow(ctx, createOIDCLink,
		arg.UserID,
		arg.OidcProviderID,
		arg.ProviderUserID,
		arg.ProviderEmail,
		arg.ProviderMetadata,
	)
	var i OidcLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OidcProviderID,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.ProviderMetadata,
		&i.LinkedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteOIDCLink = `-- name: DeleteOIDCLink :exec
DELETE FROM oidc_links
WHERE user_id = $1 AND oidc_provider_id = $2
`

type DeleteOIDCLinkParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OidcProviderID uuid.UUID `json:"oidc_provider_id"`
}

func (q *Queries) DeleteOIDCLink(ctx context.Context, arg DeleteOIDCLinkParams) error {
	_, err := q.db.Exec(ctx, deleteOIDCLink, arg.UserID, arg.OidcProviderID)
	return err
}

const getOIDCLinkByProvider = `-- name: GetOIDCLinkByProvider :one
SELECT id, user_id, oidc_provider_id, provider_user_id, provider_email, provider_metadata, linked_at, last_used_at FROM oidc_links
WHERE oidc_provider_id = $1 AND provider_user_id = $2
`

type GetOIDCLinkByProviderParams struct {
	OidcProviderID uuid.UUID `json:"oidc_provider_id"`
	ProviderUserID string    `json:"provider_user_id"`
}

func (q *Queries) GetOIDCLinkByProvider(ctx context.Context, arg GetOIDCLinkByProviderParams) (OidcLink, error) {
	row := q.db.QueryRow(ctx, getOIDCLinkByProvider, arg.OidcProviderID, arg.ProviderUserID)
	var i OidcLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OidcProviderID,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.ProviderMetadata,
		&i.LinkedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOIDCLinkByUser = `-- name: GetOIDCLinkByUser :one
SELECT id, user_id, oidc_provider_id, provider_user_id, provider_email, provider_metadata, linked_at, last_used_at FROM oidc_links
WHERE user_id = $1 AND oidc_provider_id = $2
`

type GetOIDCLinkByUserParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OidcProviderID uuid.UUID `json:"oidc_provider_id"`
}

func (q *Queries) GetOIDCLinkByUser(ctx context.Context, arg GetOIDCLinkByUserParams) (OidcLink, error) {
	row := q.db.QueryRow(ctx, getOIDCLinkByUser, arg.UserID, arg.OidcProviderID)
	var i OidcLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OidcProviderID,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.ProviderMetadata,
		&i.LinkedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listOIDCLinksByUser = `-- name: ListOIDCLinksByUser :many
SELECT id, user_id, oidc_provider_id, provider_user_id, provider_email, provider_metadata, linked_at, last_used_at FROM oidc_links
WHERE user_id = $1
ORDER BY linked_at DESC
`

func (q *Queries) ListOIDCLinksByUser(ctx context.Context, userID uuid.UUID) ([]OidcLink, error) {
	rows, err := q.db.Query(ctx, listOIDCLinksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcLink{}
	for rows.Next() {
		var i OidcLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OidcProviderID,
			&i.ProviderUserID,
			&i.ProviderEmail,
			&i.ProviderMetadata,
			&i.LinkedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOIDCLinkLastUsed = `-- name: UpdateOIDCLinkLastUsed :exec
UPDATE oidc_links
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) UpdateOIDCLinkLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateOIDCLinkLastUsed, id)
	return err
}
