// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_providers.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/travisbale/heimdall/internal/auth"
)

const createOIDCProvider = `-- name: CreateOIDCProvider :one
INSERT INTO oidc_providers (
    tenant_id,
    provider_name,
    issuer_url,
    client_id,
    client_secret,
    scopes,
    enabled,
    allowed_domains,
    auto_create_users,
    require_email_verification,
    registration_access_token,
    registration_client_uri,
    client_id_issued_at,
    client_secret_expires_at,
    registration_method
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, tenant_id, provider_name, issuer_url, client_id, client_secret, scopes, enabled, allowed_domains, auto_create_users, require_email_verification, registration_access_token, registration_client_uri, client_id_issued_at, client_secret_expires_at, registration_method, created_at, updated_at
`

type CreateOIDCProviderParams struct {
	TenantID                 uuid.UUID                   `json:"tenant_id"`
	ProviderName             string                      `json:"provider_name"`
	IssuerUrl                string                      `json:"issuer_url"`
	ClientID                 string                      `json:"client_id"`
	ClientSecret             string                      `json:"client_secret"`
	Scopes                   []string                    `json:"scopes"`
	Enabled                  bool                        `json:"enabled"`
	AllowedDomains           []string                    `json:"allowed_domains"`
	AutoCreateUsers          bool                        `json:"auto_create_users"`
	RequireEmailVerification bool                        `json:"require_email_verification"`
	RegistrationAccessToken  *string                     `json:"registration_access_token"`
	RegistrationClientUri    *string                     `json:"registration_client_uri"`
	ClientIDIssuedAt         *time.Time                  `json:"client_id_issued_at"`
	ClientSecretExpiresAt    *time.Time                  `json:"client_secret_expires_at"`
	RegistrationMethod       auth.OIDCRegistrationMethod `json:"registration_method"`
}

func (q *Queries) CreateOIDCProvider(ctx context.Context, arg CreateOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, createOIDCProvider,
		arg.TenantID,
		arg.ProviderName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.Enabled,
		arg.AllowedDomains,
		arg.AutoCreateUsers,
		arg.RequireEmailVerification,
		arg.RegistrationAccessToken,
		arg.RegistrationClientUri,
		arg.ClientIDIssuedAt,
		arg.ClientSecretExpiresAt,
		arg.RegistrationMethod,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.RequireEmailVerification,
		&i.RegistrationAccessToken,
		&i.RegistrationClientUri,
		&i.ClientIDIssuedAt,
		&i.ClientSecretExpiresAt,
		&i.RegistrationMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOIDCProvider = `-- name: DeleteOIDCProvider :exec
DELETE FROM oidc_providers
WHERE id = $1
`

func (q *Queries) DeleteOIDCProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOIDCProvider, id)
	return err
}

const getOIDCProvider = `-- name: GetOIDCProvider :one
SELECT id, tenant_id, provider_name, issuer_url, client_id, client_secret, scopes, enabled, allowed_domains, auto_create_users, require_email_verification, registration_access_token, registration_client_uri, client_id_issued_at, client_secret_expires_at, registration_method, created_at, updated_at FROM oidc_providers
WHERE id = $1
`

func (q *Queries) GetOIDCProvider(ctx context.Context, id uuid.UUID) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getOIDCProvider, id)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.RequireEmailVerification,
		&i.RegistrationAccessToken,
		&i.RegistrationClientUri,
		&i.ClientIDIssuedAt,
		&i.ClientSecretExpiresAt,
		&i.RegistrationMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOIDCProvidersByDomain = `-- name: GetOIDCProvidersByDomain :many
SELECT id, tenant_id, provider_name, issuer_url, client_id, client_secret, scopes, enabled, allowed_domains, auto_create_users, require_email_verification, registration_access_token, registration_client_uri, client_id_issued_at, client_secret_expires_at, registration_method, created_at, updated_at FROM oidc_providers
WHERE enabled = true
  AND $1 = ANY(allowed_domains)
ORDER BY created_at ASC
`

// Find all OAuth providers configured for an email domain (cross-tenant, for SSO discovery)
// This query bypasses RLS to search across all tenants
func (q *Queries) GetOIDCProvidersByDomain(ctx context.Context, allowedDomains []string) ([]OidcProvider, error) {
	rows, err := q.db.Query(ctx, getOIDCProvidersByDomain, allowedDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcProvider{}
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderName,
			&i.IssuerUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.Enabled,
			&i.AllowedDomains,
			&i.AutoCreateUsers,
			&i.RequireEmailVerification,
			&i.RegistrationAccessToken,
			&i.RegistrationClientUri,
			&i.ClientIDIssuedAt,
			&i.ClientSecretExpiresAt,
			&i.RegistrationMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCProviders = `-- name: ListOIDCProviders :many
SELECT id, tenant_id, provider_name, issuer_url, client_id, client_secret, scopes, enabled, allowed_domains, auto_create_users, require_email_verification, registration_access_token, registration_client_uri, client_id_issued_at, client_secret_expires_at, registration_method, created_at, updated_at FROM oidc_providers
WHERE tenant_id = $1 AND enabled = true
ORDER BY provider_name
`

func (q *Queries) ListOIDCProviders(ctx context.Context, tenantID uuid.UUID) ([]OidcProvider, error) {
	rows, err := q.db.Query(ctx, listOIDCProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcProvider{}
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderName,
			&i.IssuerUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.Enabled,
			&i.AllowedDomains,
			&i.AutoCreateUsers,
			&i.RequireEmailVerification,
			&i.RegistrationAccessToken,
			&i.RegistrationClientUri,
			&i.ClientIDIssuedAt,
			&i.ClientSecretExpiresAt,
			&i.RegistrationMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOIDCProvider = `-- name: UpdateOIDCProvider :one
UPDATE oidc_providers
SET
    provider_name = COALESCE($1, provider_name),
    client_secret = COALESCE($2, client_secret),
    scopes = COALESCE($3, scopes),
    enabled = COALESCE($4, enabled),
    allowed_domains = COALESCE($5, allowed_domains),
    auto_create_users = COALESCE($6, auto_create_users),
    require_email_verification = COALESCE($7, require_email_verification),
    updated_at = now()
WHERE id = $8
RETURNING id, tenant_id, provider_name, issuer_url, client_id, client_secret, scopes, enabled, allowed_domains, auto_create_users, require_email_verification, registration_access_token, registration_client_uri, client_id_issued_at, client_secret_expires_at, registration_method, created_at, updated_at
`

type UpdateOIDCProviderParams struct {
	ProviderName             *string   `json:"provider_name"`
	ClientSecret             *string   `json:"client_secret"`
	Scopes                   []string  `json:"scopes"`
	Enabled                  *bool     `json:"enabled"`
	AllowedDomains           []string  `json:"allowed_domains"`
	AutoCreateUsers          *bool     `json:"auto_create_users"`
	RequireEmailVerification *bool     `json:"require_email_verification"`
	ID                       uuid.UUID `json:"id"`
}

// Allows updating configuration and credentials
func (q *Queries) UpdateOIDCProvider(ctx context.Context, arg UpdateOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, updateOIDCProvider,
		arg.ProviderName,
		arg.ClientSecret,
		arg.Scopes,
		arg.Enabled,
		arg.AllowedDomains,
		arg.AutoCreateUsers,
		arg.RequireEmailVerification,
		arg.ID,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.RequireEmailVerification,
		&i.RegistrationAccessToken,
		&i.RegistrationClientUri,
		&i.ClientIDIssuedAt,
		&i.ClientSecretExpiresAt,
		&i.RegistrationMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
