// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: permissions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/travisbale/heimdall/sdk"
)

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, name, description, created_at
FROM permissions
WHERE id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id uuid.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT
    p.id,
    p.name,
    p.description,
    COALESCE(up.effect, 'allow') as effect  -- Default to 'allow' for role-based permissions
FROM permissions p
LEFT JOIN role_permissions rp ON rp.permission_id = p.id
LEFT JOIN user_roles ur ON ur.role_id = rp.role_id AND ur.user_id = $1
LEFT JOIN user_permissions up ON up.permission_id = p.id AND up.user_id = $1
WHERE ur.user_id = $1 OR up.user_id = $1
ORDER BY p.name
`

type GetUserPermissionsRow struct {
	ID          uuid.UUID            `json:"id"`
	Name        string               `json:"name"`
	Description string               `json:"description"`
	Effect      sdk.PermissionEffect `json:"effect"`
}

// Get all permissions for a user (from roles + direct permissions)
// Includes effect from direct permissions for deny logic
func (q *Queries) GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Effect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, description, created_at
FROM permissions
ORDER BY name
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
