// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: rate_limits.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredRateLimits = `-- name: DeleteExpiredRateLimits :exec
DELETE FROM rate_limits WHERE expires_at <= now()
`

// Swept on a schedule rather than per request: an expired row is harmless until reused.
func (q *Queries) DeleteExpiredRateLimits(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRateLimits)
	return err
}

const incrementRateLimit = `-- name: IncrementRateLimit :one
INSERT INTO rate_limits (key, count, expires_at)
VALUES ($1, 1, now() + $2::interval)
ON CONFLICT (key) DO UPDATE
SET count      = CASE WHEN rate_limits.expires_at <= now() THEN 1 ELSE rate_limits.count + 1 END,
    expires_at = CASE WHEN rate_limits.expires_at <= now() THEN now() + $2::interval ELSE rate_limits.expires_at END
RETURNING count, expires_at
`

type IncrementRateLimitParams struct {
	Key    string          `json:"key"`
	Window pgtype.Interval `json:"window"`
}

type IncrementRateLimitRow struct {
	Count     int64     `json:"count"`
	ExpiresAt time.Time `json:"expires_at"`
}

// A window is reused in place once it has expired, so a key holds one row for its
// lifetime and the count resets without a delete.
func (q *Queries) IncrementRateLimit(ctx context.Context, arg IncrementRateLimitParams) (IncrementRateLimitRow, error) {
	row := q.db.QueryRow(ctx, incrementRateLimit, arg.Key, arg.Window)
	var i IncrementRateLimitRow
	err := row.Scan(&i.Count, &i.ExpiresAt)
	return i, err
}

const peekRateLimit = `-- name: PeekRateLimit :one
SELECT (CASE WHEN expires_at <= now() THEN 0 ELSE count END)::bigint AS count, expires_at
FROM rate_limits
WHERE key = $1
`

type PeekRateLimitRow struct {
	Count     int64     `json:"count"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) PeekRateLimit(ctx context.Context, key string) (PeekRateLimitRow, error) {
	row := q.db.QueryRow(ctx, peekRateLimit, key)
	var i PeekRateLimitRow
	err := row.Scan(&i.Count, &i.ExpiresAt)
	return i, err
}

const resetRateLimit = `-- name: ResetRateLimit :exec
DELETE FROM rate_limits WHERE key = $1
`

func (q *Queries) ResetRateLimit(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, resetRateLimit, key)
	return err
}
