// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.name, p.description, rp.created_at as assigned_at
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.name
`

type GetRolePermissionsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	AssignedAt  time.Time `json:"assigned_at"`
}

func (q *Queries) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRolePermissionsRow{}
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRolePermissions = `-- name: InsertRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_id, tenant_id)
SELECT $1::uuid, unnest($2::uuid[]), r.tenant_id
FROM roles r
WHERE r.id = $1::uuid
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type InsertRolePermissionsParams struct {
	Column1 uuid.UUID   `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
}

// Insert multiple permissions for a role (called after SetRolePermissions in transaction)
func (q *Queries) InsertRolePermissions(ctx context.Context, arg InsertRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, insertRolePermissions, arg.Column1, arg.Column2)
	return err
}

const setRolePermissions = `-- name: SetRolePermissions :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

// Replace all permissions for a role (used for bulk updates)
// First delete all existing permissions, then insert new ones
// Note: This should be called in a transaction with InsertRolePermissions
func (q *Queries) SetRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setRolePermissions, roleID)
	return err
}
