// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: trusted_devices.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTrustedDevice = `-- name: CreateTrustedDevice :one
INSERT INTO trusted_devices (user_id, tenant_id, token_hash, user_agent, ip_address, expires_at)
VALUES ($1, current_tenant_id(), $2, $3, $4, $5)
RETURNING id, user_id, tenant_id, token_hash, user_agent, ip_address, created_at, last_used_at, expires_at, revoked_at
`

type CreateTrustedDeviceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	UserAgent string    `json:"user_agent"`
	IpAddress string    `json:"ip_address"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateTrustedDevice(ctx context.Context, arg CreateTrustedDeviceParams) (TrustedDevice, error) {
	row := q.db.QueryRow(ctx, createTrustedDevice,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i TrustedDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredTrustedDevices = `-- name: DeleteExpiredTrustedDevices :exec
DELETE FROM trusted_devices
WHERE expires_at < now() OR revoked_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredTrustedDevices(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTrustedDevices)
	return err
}

const getTrustedDeviceByTokenHash = `-- name: GetTrustedDeviceByTokenHash :one
SELECT id, user_id, tenant_id, token_hash, user_agent, ip_address, created_at, last_used_at, expires_at, revoked_at FROM trusted_devices
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetTrustedDeviceByTokenHash(ctx context.Context, tokenHash string) (TrustedDevice, error) {
	row := q.db.QueryRow(ctx, getTrustedDeviceByTokenHash, tokenHash)
	var i TrustedDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserTrustedDevices = `-- name: RevokeAllUserTrustedDevices :exec
UPDATE trusted_devices SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserTrustedDevices(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTrustedDevices, userID)
	return err
}

const updateTrustedDeviceLastUsed = `-- name: UpdateTrustedDeviceLastUsed :exec
UPDATE trusted_devices
SET last_used_at = now(), expires_at = $2, ip_address = $3
WHERE id = $1
`

type UpdateTrustedDeviceLastUsedParams struct {
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
	IpAddress string    `json:"ip_address"`
}

func (q *Queries) UpdateTrustedDeviceLastUsed(ctx context.Context, arg UpdateTrustedDeviceLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateTrustedDeviceLastUsed, arg.ID, arg.ExpiresAt, arg.IpAddress)
	return err
}
