// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/travisbale/heimdall/internal/iam"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    tenant_id,
    email,
    password_hash,
    first_name,
    last_name,
    status
) VALUES (
    current_tenant_id(), $1, $2, $3, $4, $5
) RETURNING id, tenant_id, email, password_hash, first_name, last_name, status, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Status       iam.UserStatus `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deleteOldUnverifiedUsers = `-- name: DeleteOldUnverifiedUsers :exec
DELETE FROM users
WHERE status = 'unverified'
  AND created_at < (now() - make_interval(days => $1))
`

func (q *Queries) DeleteOldUnverifiedUsers(ctx context.Context, days int32) error {
	_, err := q.db.Exec(ctx, deleteOldUnverifiedUsers, days)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, email, password_hash, first_name, last_name, status, created_at, updated_at, last_login_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, first_name, last_name, status, created_at, updated_at, last_login_at
FROM users
WHERE email = $1 AND status != 'inactive'
ORDER BY (status = 'active') DESC, created_at DESC
LIMIT 1
`

// The index on email is partial, so a deactivated row and a live one can hold one address
// at once — an address is handed to whoever holds the job now. Unordered, this returns
// whichever row the scan reached first, which is the one the address used to belong to.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsersByEmail = `-- name: ListUsersByEmail :many
SELECT id, tenant_id, email, password_hash, first_name, last_name, status, created_at, updated_at, last_login_at
FROM users
WHERE email = $1 AND status != 'inactive'
`

// Every tenant's, and every row rather than the one that sorts first: a caller asking whether
// an address is free needs the ones a LIMIT 1 would hide behind another tenant's.
func (q *Queries) ListUsersByEmail(ctx context.Context, email string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET password_hash = COALESCE($1, password_hash),
    status = COALESCE($2, status),
    updated_at = now()
WHERE id = $3
RETURNING id, tenant_id, email, password_hash, first_name, last_name, status, created_at, updated_at, last_login_at
`

type UpdateUserParams struct {
	PasswordHash *string         `json:"password_hash"`
	Status       *iam.UserStatus `json:"status"`
	ID           uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.PasswordHash, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
