// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_permissions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/travisbale/heimdall/sdk"
)

const deleteAllDirectPermissions = `-- name: DeleteAllDirectPermissions :exec
DELETE FROM user_permissions
WHERE user_id = $1
`

// Replace all direct permissions for a user (used for bulk updates)
// Note: This should be called in a transaction with InsertDirectPermissions
func (q *Queries) DeleteAllDirectPermissions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllDirectPermissions, userID)
	return err
}

const getDirectPermissions = `-- name: GetDirectPermissions :many
SELECT p.id, p.name, p.description, up.effect
FROM permissions p
JOIN user_permissions up ON up.permission_id = p.id
WHERE up.user_id = $1
ORDER BY p.name
`

type GetDirectPermissionsRow struct {
	ID          uuid.UUID            `json:"id"`
	Name        string               `json:"name"`
	Description string               `json:"description"`
	Effect      sdk.PermissionEffect `json:"effect"`
}

// Get direct permissions assigned to user (not from roles)
func (q *Queries) GetDirectPermissions(ctx context.Context, userID uuid.UUID) ([]GetDirectPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getDirectPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDirectPermissionsRow{}
	for rows.Next() {
		var i GetDirectPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Effect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDirectPermissions = `-- name: InsertDirectPermissions :exec
INSERT INTO user_permissions (user_id, permission_id, effect)
SELECT $1::uuid, unnest($2::uuid[]), unnest($3::varchar[])::permission_effect
`

type InsertDirectPermissionsParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	PermissionIds []uuid.UUID `json:"permission_ids"`
	Effects       []string    `json:"effects"`
}

// Insert multiple direct permissions for a user (called after SetDirectPermissions in transaction)
// Parameters: user_id, permission_ids array, effects array (strings cast to permission_effect)
func (q *Queries) InsertDirectPermissions(ctx context.Context, arg InsertDirectPermissionsParams) error {
	_, err := q.db.Exec(ctx, insertDirectPermissions, arg.UserID, arg.PermissionIds, arg.Effects)
	return err
}
