// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: user_roles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteAllUserRoles = `-- name: DeleteAllUserRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
`

// Replace all roles for a user (used for bulk updates)
// Note: This should be called in a transaction with InsertUserRoles
func (q *Queries) DeleteAllUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserRoles, userID)
	return err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.description, r.mfa_required
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

type GetUserRolesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	MfaRequired bool      `json:"mfa_required"`
}

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesRow{}
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MfaRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserRoles = `-- name: InsertUserRoles :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1::uuid, unnest($2::uuid[])
ON CONFLICT (user_id, role_id) DO NOTHING
`

type InsertUserRolesParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	RoleIds []uuid.UUID `json:"role_ids"`
}

// Insert multiple roles for a user (called after SetUserRoles in transaction)
// Parameters: user_id, role_ids array
func (q *Queries) InsertUserRoles(ctx context.Context, arg InsertUserRolesParams) error {
	_, err := q.db.Exec(ctx, insertUserRoles, arg.UserID, arg.RoleIds)
	return err
}
