// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: verification_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (
    user_id,
    token,
    expires_at
) VALUES (
    $1, $2, $3
) ON CONFLICT (user_id) DO UPDATE
SET token = EXCLUDED.token,
    expires_at = EXCLUDED.expires_at,
    created_at = now()
RETURNING user_id, token, expires_at, created_at
`

type CreateVerificationTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i VerificationToken
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredVerificationTokens = `-- name: DeleteExpiredVerificationTokens :exec
DELETE FROM verification_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredVerificationTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerificationTokens)
	return err
}

const deleteVerificationToken = `-- name: DeleteVerificationToken :exec
DELETE FROM verification_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteVerificationToken(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationToken, userID)
	return err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT user_id, token, expires_at, created_at
FROM verification_tokens
WHERE token = $1
`

func (q *Queries) GetVerificationToken(ctx context.Context, token string) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, token)
	var i VerificationToken
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
